=== Ivana98/xml-tim1/backend/obavestenjecir.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/obavestenjecir"
    xmlns:ftn="http://www.ftn.uns.ac.rs/obavestenjecir">
    <xs:element name="Obavestenje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Osnovni_podaci">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="ftn:Organ"/>
                            <xs:element minOccurs="1" name="Broj_predmeta">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Datum">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date">
                                            <xs:attribute name="property" type="xs:string"/>
                                            <xs:attribute name="datatype" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="ftn:Podnosioc_zahteva"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Sadrzaj">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Naslov" type="xs:string"/>
                            <xs:element name="Podnaslov" type="xs:string"/>
                            <xs:element ref="ftn:Paragraf"/>
                            <xs:element ref="ftn:Dostavljeno"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Organ">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Naziv">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                                <xs:attribute name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Sediste">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                                <xs:attribute name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Podnosioc_zahteva">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ime">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                                <xs:attribute name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Prezime">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                                <xs:attribute name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Naziv" type="xs:string"/>
                <xs:element name="Adresa">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                                <xs:attribute name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Paragraf">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="Godina" type="xs:gYear"/>
                <xs:element name="Opis_informacije" type="xs:string"/>
                <xs:element name="Datum_uvida">
                    <xs:simpleType>
                        <xs:restriction base="xs:date"/>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Vreme_uvida" type="xs:time"/>
                <xs:element name="Pocetak_cas" type="xs:time"/>
                <xs:element name="Kraj_cas" type="xs:time"/>
                <xs:element name="Grad_organa" type="xs:string"/>
                <xs:element name="Ulica_organa" type="xs:string"/>
                <xs:element name="Broj_organa" type="xs:string"/>
                <xs:element name="Broj_kancelarije" type="xs:string"/>
                <xs:element name="Iznos_troskova">
                    <xs:simpleType>
                        <xs:restriction base="xs:double">
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Select">
        <xs:sequence>
            <xs:element maxOccurs="2" name="Primer">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="ID" type="xs:int"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="Selected" type="xs:int"/>
    </xs:complexType>
    <xs:element name="Dostavljeno" type="ftn:Select"/>
</xs:schema>

=== Ivana98/xml-tim1/documents/xml_documents/obavestenje2.xml
<?xml version="1.0" encoding="UTF-8"?>

<Obavestenje xmlns="http://www.ftn.uns.ac.rs/obavestenjecir"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/obavestenjecir ../xsd_documents/obavestenjecir.xsd"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
    <Osnovni_podaci>
        <Organ>
            <Naziv property="pred:nazivOrgana" datatype="xs:string">Naziv organa</Naziv>
            <Sediste property="pred:sedisteOrgana" datatype="xs:string">Kikinda</Sediste>
        </Organ>
        <Broj_predmeta>5</Broj_predmeta>
        <Datum property="pred:datum" datatype="xs:date">2021-01-02</Datum>
        <Podnosioc_zahteva>
            <Ime property="pred:imePodnosioca" datatype="xs:string">Marija</Ime>
            <Prezime property="pred:prezimePodnosioca" datatype="xs:string">Curcic</Prezime>
            <Naziv>Naziv 2</Naziv>
            <Adresa property="pred:adresaPodnosioca" datatype="xs:string">Teodora Drajzera</Adresa>
        </Podnosioc_zahteva>
    </Osnovni_podaci>
    
    <Sadrzaj>
        <Naslov>O B A V E S T E N J E 2</Naslov>
        <Podnaslov>о стављању на увид документа који садржи
            тражену информацију и о изради копије
        </Podnaslov>

        <Paragraf>
            Paragraf za Obavestenje 2
            <Godina>2021</Godina> год., којим сте тражили увид у документ/е са информацијама о / у вези са: 
            <Opis_informacije>...opis...</Opis_informacije>
            обавештавамо вас да дана <Datum_uvida>2020-01-03</Datum_uvida>, u <Vreme_uvida>13:00:00</Vreme_uvida> часова, односно у времену од <Pocetak_cas>15:00:00</Pocetak_cas> do 
            <Kraj_cas>16:20:00</Kraj_cas> часова, у просторијама органа у <Grad_organa>Novi Sad</Grad_organa> ул. <Ulica_organa>Misiceva</Ulica_organa> бр. 
            <Broj_organa>3</Broj_organa>, канцеларија бр. <Broj_kancelarije>12a</Broj_kancelarije> можете извршити увид у документ/е у коме је садржана 
            тражена информација.

            Том приликом, на ваш захтев, може вам се издати и копија документа са траженом информацијом.

            Трошкови су утврђени Уредбом Владе Републике Србије („Сл. гласник РС“, бр. 8/06), и то: 
            копија стране А4 формата износи 3 динара, А3 формата 6 динара, CD 35 динара, дискете 20 
            динара, DVD 40 динара, аудио-касета – 150 динара, видео-касета 300 динара, претварање 
            једне стране документа из физичког у електронски облик – 30 динара.

            Износ укупних трошкова израде копије документа по вашем захтеву износи <Iznos_troskova>500</Iznos_troskova>
            динара и уплаћује се на жиро-рачун Буџета Републике Србије бр. 840-742328-843-30, с 
            позивом на број 97 – ознака шифре општине/града где се налази орган власти (из 
            Правилника о условима и начину вођења рачуна – „Сл. гласник РС“, 20/07... 40/10).
        </Paragraf>
        
        
        <Dostavljeno Selected="2">
            <Primer ID="1">1. Именованом </Primer>
            <Primer ID="2">2. Архиви</Primer>
        </Dostavljeno>
    </Sadrzaj>
</Obavestenje>
