=== Ivana98/xml-tim1/backend/zahtev.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/zahtev" xmlns:ftn="http://www.ftn.uns.ac.rs/zahtev">
    <xs:element name="zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ftn:info_organa"/>
                <xs:element name="naslov" type="xs:string"/>
                <xs:element name="svrha_zahteva" type="xs:string"/>
                <xs:element ref="ftn:opis_zahteva"/>
                <xs:element name="mesto" type="xs:string"/>
                <xs:element name="datum">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute name="property" type="xs:string"/>
                                <xs:attribute name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="ftn:trazilac"/>
                <xs:element name="footer" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="info_organa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naziv" type="xs:string"/>
                <xs:element name="sediste" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="opis_zahteva">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tekst_zahteva" type="xs:string"/>
                <xs:element name="tipovi_zahteva">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="ftn:tip_zahteva"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dodatne_informacije">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="opis_dodatne_informacije" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="tip_zahteva">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="nacini_slanja">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="1" ref="ftn:nacin_slanja"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="selektovan" type="xs:boolean"/>
            <xs:attribute name="rb" type="xs:int"/>
            <xs:attribute name="tekst" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="nacin_slanja">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="detaljan_opis" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="rb" type="xs:int"/>
            <xs:attribute default="false" name="selektovan" type="xs:boolean"/>
            <xs:attribute name="tekst" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="trazilac">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ime_i_prezime">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                                <xs:attribute name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="adresa">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                                <xs:attribute name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="kontakt" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Ivana98/xml-tim1/documents/xml_documents/zahtev.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<zahtev xmlns="http://www.ftn.uns.ac.rs/zahtev"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/zahtev ../xsd_documents/zahtev.xsd"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/"
    about="http://www.ftn.uns.ac.rs/rdf/zahtev/Zahtev"
    property="pred:status" datatype="xs:string" content="na cekanju">
    <info_organa about="http://www.ftn.uns.ac.rs/rdf/zahtev/Organ">
        <naziv property="pred:naziv" datatype="xs:string">organ1</naziv>
        <sediste property="pred:sediste" datatype="xs:string">Novi Sad</sediste>
    </info_organa>
    <naslov>Zahtev</naslov>
    <svrha_zahteva>Pristup informaciji od javnog znacaja</svrha_zahteva>
    <opis_zahteva>
        <tekst_zahteva>na osnovu clana X zahtevam sledece:</tekst_zahteva>
        <tipovi_zahteva>
            <tip_zahteva selektovan="true" rb="1" tekst="zelim uvid u dokument ..."/>
            <tip_zahteva selektovan="false" rb="2" tekst="zelim da mi posaljete dokument ...">
                <nacini_slanja>
                    <nacin_slanja rb="1" selektovan="false" tekst="elektronski"/>
                </nacini_slanja>
            </tip_zahteva>
        </tipovi_zahteva>
        <dodatne_informacije>Ovaj zahtev se odnosi na sledece info: <opis_dodatne_informacije>Trazim informaciju tu i tu pod rednim brojem tim.</opis_dodatne_informacije>
        </dodatne_informacije>
    </opis_zahteva>
    <mesto property="pred:mesto" datatype="xs:string">Novi Sad</mesto>
    <datum property="pred:datum" datatype="xs:date">2021-01-30+01:00</datum>
    <trazilac about="http://www.ftn.uns.ac.rs/rdf/zahtev/Trazilac">
        <ime_i_prezime property="pred:ime-prezime" datatype="xs:string">Nikola Jokic</ime_i_prezime>
        <adresa property="pred:mesto" datatype="xs:string">Sombor, somborska 5</adresa>
        <kontakt>063 645658</kontakt>
    </trazilac>
    <footer>ovo je tekst footer-a</footer>
</zahtev>
