=== Ivana98/xml-tim1/documents/xsd_documents/zalbanaodlukucir.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/zalba-na-odluku"
    xmlns:ftn="http://www.ftn.uns.ac.rs/zalba-na-odluku">

    <xs:element name="zalba_na_odluku">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ftn:naslov"/>
                <xs:element ref="ftn:podaci_o_povereniku"/>
                <xs:element ref="ftn:zalba"/>
                <xs:element ref="ftn:napomene"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="naslov" type="xs:string"/>
    <xs:element name="zalba">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="podnaslov" type="xs:string"/>
                <xs:element ref="ftn:zalilac"/>
                <xs:element name="naziv_organa" type="xs:string"/>
                <xs:element ref="ftn:zahtev"/>
                <xs:element ref="ftn:sadrzaj"/>
                <xs:element ref="ftn:podnosilac"/>
                <xs:element ref="ftn:vreme_i_mesto"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="sadrzaj">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datum" type="xs:date"/>
                <xs:element name="deo_odluke" type="xs:string"/>
                <xs:element name="zakon" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="broj_zahteva" type="xs:int"/>
                <xs:element name="godina" type="xs:gYear"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="podaci_o_povereniku">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="namena" type="xs:string"/>
                <xs:element ref="ftn:adresa"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="zalilac">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ime" type="xs:string"/>
                <xs:element name="prezime" type="xs:string"/>
                <xs:element name="naziv" type="xs:string"/>
                <xs:element ref="ftn:adresa"/>
                <xs:element name="sediste" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="podnosilac">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ime" type="xs:string"/>
                <xs:element name="prezime" type="xs:string"/>
                <xs:element ref="ftn:adresa"/>
                <xs:element name="kontakt_podaci" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="napomene">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="napomena">
                    <xs:complexType>
                        <xs:attribute name="id" type="xs:long"/>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="ftn:naslov"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="vreme_i_mesto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="grad" type="xs:string"/>
                <xs:element name="datum" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="grad" type="xs:string"/>
                <xs:element name="ulica" type="xs:string"/>
                <xs:element name="broj" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Ivana98/xml-tim1/documents/xml_documents/zalbaodluka2.xml
<?xml version="1.0" encoding="UTF-8"?>
<zalba_na_odluku
    xmlns="http://www.ftn.uns.ac.rs/zalba-na-odluku"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/zalba-na-odluku ../xsd_documents/zalbanaodlukucir.xsd"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">>
    <naslov> ЖАЛБА  ПРОТИВ  ОДЛУКЕ 2 </naslov>
    
    <podaci_o_povereniku>
        <namena> 
            Поверенику за информације од јавног значаја и заштиту података о личности 
        </namena>
        <adresa>
            <grad property="pred:grad" datatype="xs:string"> Београд </grad>
            <ulica property="pred:ulica" datatype="xs:string"> Булевар краља Александрa </ulica>
            <broj>15</broj>
        </adresa>
    </podaci_o_povereniku>
    
    <zalba>
        Ж А Л Б А  
        <zalilac type = "TFizickoLice">
            <adresa>
                <grad></grad>
                <ulica></ulica>
                <broj></broj>
            </adresa>
            <sediste></sediste>
            <ime></ime>
            <prezime></prezime>
        </zalilac>
        против решења-закључка 
        
        <naziv_organa></naziv_organa>
        Број <broj_zahteva>3</broj_zahteva> од <godina>2020</godina> године.
        
        <sadrzaj>
            Sadrzaj zalbe na odluku <datum>2020-12-30</datum> Oдлуку побијам у
            целости, односно у делу којим <deo_odluke> deo </deo_odluke> јер није заснована на Закону о слободном приступу информацијама од јавног значаја.
            На основу изнетих разлога, предлажем да Повереник уважи моју жалбу,  поништи
            одлука првостепеног органа и омогући ми приступ траженој/им  информацији/ма.
            Жалбу подносим благовремено, у законском року утврђеном у <zakon>члану 22. ст. 1. Закона о слободном приступу информацијама од јавног значаја.</zakon>   
        </sadrzaj>
        
        <podnosilac>
            <ime property="pred:imePodnosioca" datatype="xs:string">Ime</ime>
            <prezime property="pred:prezimePodnosioca" datatype="xs:string">Prezime</prezime>
            <adresa>
                <grad property="pred:gradPodnosioca" datatype="xs:string"></grad>
                <ulica></ulica>
                <broj></broj>
            </adresa>
            <kontakt_podaci>0651224720</kontakt_podaci>
        </podnosilac>
        
        <vreme_i_mesto>
            <grad property="pred:mestoPodnosenja" datatype="xs:string"></grad>
            <datum property="pred:datumPodnosenja" datatype="xs:date">2020-12-21</datum>
        </vreme_i_mesto>
        
    </zalba>
    
    <napomene>
        Напомена: 
        <napomena id="1">
            Napomena 1
        </napomena>
        <napomena id="2">
            Napomena 2
        </napomena>
    </napomene>
    
</zalba_na_odluku>
